server:
  address: localhost
  port: 8081
  servlet:
    context-path: /mybatis

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wzc
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    connect-timeout: 30000

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.po


